[project]
name = "full-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.1",
    "docx2txt>=0.9",
    "fastapi>=0.121.2",
    "langchain>=1.2.6",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.7",
    "langchain-text-splitters>=1.1.0",
    "llama-index>=0.14.8",
    "llama-index-embeddings-openai>=0.5.1",
    "llama-index-postprocessor-cohere-rerank>=0.5.1",
    "llama-index-vector-stores-qdrant>=0.8.8",
    "llama-parse>=0.6.54",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "pyjwt>=2.10.1",
    "pymupdf-layout>=1.26.6",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "qdrant-client>=1.15.1",
    "requests>=2.32.5",
    "streamlit>=1.51.0",
    "uvicorn>=0.38.0",
]
